name: CI/CD with dbt and PostgreSQL

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  dbt:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Create Python virtual environment
      run: python3 -m venv dbt-env

    - name: Activate virtual environment and install dependencies
      run: |
        source dbt-env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create profiles.yml
      run: |
        mkdir -p ~/.dbt
        echo "default:" > ~/.dbt/profiles.yml
        echo "  target: dev" >> ~/.dbt/profiles.yml
        echo "  outputs:" >> ~/.dbt/profiles.yml
        echo "    dev:" >> ~/.dbt/profiles.yml
        echo "      type: postgres" >> ~/.dbt/profiles.yml
        echo "      host: localhost" >> ~/.dbt/profiles.yml
        echo "      user: postgres" >> ~/.dbt/profiles.yml
        echo "      pass: postgres" >> ~/.dbt/profiles.yml
        echo "      port: 5432" >> ~/.dbt/profiles.yml
        echo "      dbname: test_db" >> ~/.dbt/profiles.yml

    - name: Initialize dbt project
      run: |
        source dbt-env/bin/activate
        dbt init --profiles-dir ~/.dbt

    - name: check dbt project
      run: |
        source dbt-env/bin/activate
        dbt debug
        
    - name: Extract data and upload it to DB
      run: |
        source dbt-env/bin/activate
        python -m extract

    - name: Run dbt run
      run: |
        source dbt-env/bin/activate
        dbt run